### ISSUE TITLE
unable to authenticate

### ISSUE THREAD

**Issue by FocusDesigner** [privacyidea/privacyidea-pam#3]
Hi there, 

I was able to compile the new pam module and included it in the /etc/pam.d/sshd with

`auth required /path/to/pam_privacyidea.so url=https://privacy.server debug nossl` 

Challenge Response is enabled. NOSSL is enabled because of a selfsigned cert in my testing environment

When I now try to login, I get the OTP prompt as 2nd factor as expected, but sadly the authentication is denied, with the following error in the logs:

`ERR904: the user can not be found in any resolver in this realm!`

As the password is successfully checked against the Realm in the first step, I'm actually a bit confused about this error.
Does anyone know what I'm doing wrong?

**Comment by nilsbehlen** [comment]
> As the password is successfully checked against the Realm in the first step

Against what realm? You are not sending a request to privacyidea prior to the OTP, so i guess you are talking about the module before pam_privacyidea. 
The error you are seeing is from privacyidea, which did not find the user. So this is probably a configuration problem in your privacyidea.

**Comment by nilsbehlen** [comment]
Are you sending a realm when using the credential provider?
By default this module does 1 request (if using classic OTP), if you configure sendEmptyPass or sendPassword, it will do another request prior to asking for OTP to possibly trigger challenges.
I do not know how the rest of your sshd pam config looks like, but the message u have seen on the log probably was from another module. You can also check the request in the privacyidea audit log to see that the user was transmitted correctly, but it probably was since the error message is not "please specify a user" or something like that.

**Comment by nilsbehlen** [comment]
Yes it happens in the CP. This module just sends the "input" from the username to privacyidea. The evaluation in PI is depending on the configuration, which is also not my expertise.
